[application]

# App (Project) Name
name = "slides-jug-summer-camp-24"

# Dioxus App Default Platform
# web, desktop, fullstack
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# assets file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "Et si on écrivait nos Web Components en Rust ?"

base_path = "slides-jug-summer-camp-24"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# CSS style file

style = [
  # Fonts
  "https://fonts.googleapis.com/css2?family=Inconsolata:wght@200..900&family=Mulish:ital,wght@0,200..1000;1,200..1000&family=Quicksand:wght@300..700&display=swap",

  # Pico
  "/slides-jug-summer-camp-24/pico.min.css",
  "/slides-jug-summer-camp-24/pico.colors.min.css",

  # PrismJS
  "/slides-jug-summer-camp-24/prismjs/prism.css",

  # XTermJs
  "/slides-jug-summer-camp-24/xtermjs/xterm.css",

  # Custom
  "/slides-jug-summer-camp-24/main.css",
  "/slides-jug-summer-camp-24/livecode.css",
  # "/slides-jug-summer-camp-24/jugsummercamp.css",
  "/slides-jug-summer-camp-24/gdg-tls.css",
  "/slides-jug-summer-camp-24/print.css",
]

# Javascript code file
script = [
  # PrismJS
  "/slides-jug-summer-camp-24/prismjs/prism.js",
  # XTermJs
  "/slides-jug-summer-camp-24/xtermjs/xterm.js",
  "/slides-jug-summer-camp-24/xtermjs/addon-attach.js",
  "/slides-jug-summer-camp-24/xtermjs/addon-clipboard.js",
  "/slides-jug-summer-camp-24/xtermjs/addon-fit.js",
  "/slides-jug-summer-camp-24/xtermjs/addon-ligatures.js",
  "/slides-jug-summer-camp-24/xtermjs/addon-unicode11.js",
  "/slides-jug-summer-camp-24/xtermjs/addon-web-links.js",
]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
